version: '3.8'

services:
  # 1. Database (Postgres)
  db:
    image: postgres:15
    container_name: glance-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=glance_db
      - POSTGRES_USER=glance_user
      - POSTGRES_PASSWORD=glance_pass
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: glance-backend
    # Change this line to run your script!
    command: ./entrypoint.sh
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    environment:
      - POSTGRES_DB=glance_db        # Match your settings.py keys
      - POSTGRES_USER=glance_user
      - POSTGRES_PASSWORD=glance_pass
      - DB_HOST=db
      - DB_PORT=5432
    ports: # Add this so you can reach the API from your browser
      - "8000:8000"
    depends_on:
      - db

  # 3. Vue Frontend
  frontend:
    build: ./frontend
    container_name: glance-frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: